CREATE TABLE IF NOT EXISTS schema_meta (
  db_schema_version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL,
  app_version TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  project_id TEXT PRIMARY KEY,
  timezone TEXT NOT NULL,
  config_hash TEXT NOT NULL,
  config_schema_version INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS properties (
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  property_type TEXT NOT NULL DEFAULT 'url_prefix',
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  PRIMARY KEY (project_id, property_id),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sources (
  project_id TEXT NOT NULL,
  source TEXT NOT NULL,
  enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
  required INTEGER NOT NULL CHECK (required IN (0, 1)),
  source_config_json TEXT NOT NULL,
  PRIMARY KEY (project_id, source),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS collection_runs (
  run_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  timezone TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL CHECK (status IN ('running', 'complete', 'partial', 'failed')),
  config_hash TEXT NOT NULL,
  cli_version TEXT NOT NULL,
  db_schema_version INTEGER NOT NULL,
  config_schema_version INTEGER NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS source_requests (
  request_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  source TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL UNIQUE,
  request_descriptor_json TEXT NOT NULL,
  attempt INTEGER NOT NULL CHECK (attempt >= 1),
  queried_at TEXT NOT NULL,
  completed_at TEXT,
  transport_status TEXT NOT NULL CHECK (transport_status IN ('success', 'partial', 'failed', 'cancelled', 'abandoned')),
  freshness TEXT NOT NULL CHECK (freshness IN ('provisional', 'final', 'stale')),
  sampled INTEGER NOT NULL DEFAULT 0 CHECK (sampled IN (0, 1)),
  sample_share REAL,
  data_lag_seconds INTEGER,
  row_limit INTEGER,
  rows_received INTEGER,
  pages_expected INTEGER,
  pages_received INTEGER,
  error_code TEXT,
  error_summary TEXT,
  FOREIGN KEY (run_id) REFERENCES collection_runs(run_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_source_requests_logical ON source_requests(logical_observation_key);

CREATE TABLE IF NOT EXISTS raw_artifacts (
  artifact_id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL,
  relative_path TEXT NOT NULL UNIQUE,
  sha256 TEXT NOT NULL,
  content_type TEXT NOT NULL,
  compression TEXT NOT NULL DEFAULT 'none',
  redaction_state TEXT NOT NULL CHECK (redaction_state IN ('allowlist_serialized', 'redacted')),
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS metric_coverage (
  coverage_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  dimension_scope_json TEXT NOT NULL,
  dimension_scope_hash TEXT NOT NULL,
  transport_status TEXT NOT NULL CHECK (transport_status IN ('success', 'partial', 'failed', 'cancelled', 'abandoned')),
  dataset_coverage TEXT NOT NULL CHECK (dataset_coverage IN ('complete', 'truncated', 'privacy_thresholded', 'unknown', 'unavailable')),
  zero_confirmed INTEGER NOT NULL CHECK (zero_confirmed IN (0, 1)),
  expected_rows INTEGER,
  received_rows INTEGER,
  coverage_denominator INTEGER,
  coverage_ratio REAL,
  sampled INTEGER NOT NULL DEFAULT 0 CHECK (sampled IN (0, 1)),
  sample_share REAL,
  available_through TEXT,
  as_of TEXT,
  request_id TEXT NOT NULL,
  UNIQUE (logical_observation_key, metric_name, dimension_scope_hash, request_id),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS search_performance (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL,
  source TEXT NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  effective_instant_start TEXT NOT NULL,
  effective_instant_end TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  query_id TEXT NOT NULL,
  query_text TEXT NOT NULL,
  page_id TEXT NOT NULL,
  page_url TEXT NOT NULL,
  search_engine TEXT NOT NULL,
  device TEXT NOT NULL DEFAULT '__all__',
  country TEXT NOT NULL DEFAULT '__all__',
  region TEXT NOT NULL DEFAULT '__all__',
  segment_id TEXT NOT NULL DEFAULT '__all__',
  impressions INTEGER NOT NULL CHECK (impressions >= 0),
  clicks INTEGER NOT NULL CHECK (clicks >= 0),
  ctr REAL NOT NULL CHECK (ctr >= 0),
  average_position REAL,
  dataset_coverage TEXT NOT NULL CHECK (dataset_coverage IN ('complete', 'truncated', 'privacy_thresholded', 'unknown', 'unavailable')),
  sampled INTEGER NOT NULL DEFAULT 0 CHECK (sampled IN (0, 1)),
  sample_share REAL,
  freshness TEXT NOT NULL CHECK (freshness IN ('provisional', 'final', 'stale')),
  comparability TEXT NOT NULL CHECK (comparability IN ('comparable', 'config_break', 'protocol_break', 'population_mismatch', 'insufficient_history', 'window_mismatch')),
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  supersedes_fact_id INTEGER,
  superseded_by_fact_id INTEGER,
  content_hash TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_fact_id) REFERENCES search_performance(fact_id) ON DELETE RESTRICT,
  FOREIGN KEY (superseded_by_fact_id) REFERENCES search_performance(fact_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_search_performance_current
  ON search_performance(
    logical_observation_key, effective_start, effective_end, query_id, page_id,
    search_engine, device, country, region, segment_id
  )
  WHERE is_current = 1;

CREATE TABLE IF NOT EXISTS keyword_demand (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  source TEXT NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  effective_instant_start TEXT NOT NULL,
  effective_instant_end TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  keyword_id TEXT NOT NULL,
  region TEXT NOT NULL DEFAULT '__all__',
  device TEXT NOT NULL DEFAULT '__all__',
  demand_type TEXT NOT NULL,
  history_bucket TEXT NOT NULL,
  relation TEXT NOT NULL DEFAULT '__all__',
  demand_count INTEGER NOT NULL CHECK (demand_count >= 0),
  dataset_coverage TEXT NOT NULL,
  freshness TEXT NOT NULL,
  comparability TEXT NOT NULL,
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  supersedes_fact_id INTEGER,
  superseded_by_fact_id INTEGER,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_fact_id) REFERENCES keyword_demand(fact_id) ON DELETE RESTRICT,
  FOREIGN KEY (superseded_by_fact_id) REFERENCES keyword_demand(fact_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS serp_results (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  source TEXT NOT NULL,
  effective_at TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  protocol_slot TEXT NOT NULL,
  keyword_set_id TEXT NOT NULL,
  keyword_id TEXT NOT NULL,
  region TEXT NOT NULL DEFAULT '__all__',
  device TEXT NOT NULL DEFAULT '__all__',
  search_engine TEXT NOT NULL,
  rank INTEGER NOT NULL CHECK (rank >= 1),
  result_url TEXT NOT NULL,
  normalized_domain TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  result_type TEXT NOT NULL DEFAULT 'organic',
  serp_features_json TEXT NOT NULL DEFAULT '{}',
  belongs_to_project INTEGER NOT NULL DEFAULT 0 CHECK (belongs_to_project IN (0, 1)),
  dataset_coverage TEXT NOT NULL,
  freshness TEXT NOT NULL,
  comparability TEXT NOT NULL,
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS traffic_metrics (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL,
  source TEXT NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  effective_instant_start TEXT NOT NULL,
  effective_instant_end TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT '__all__',
  search_engine TEXT NOT NULL DEFAULT '__all__',
  landing_page_id TEXT NOT NULL DEFAULT '__all__',
  device TEXT NOT NULL DEFAULT '__all__',
  region TEXT NOT NULL DEFAULT '__all__',
  attribution_model TEXT NOT NULL,
  visits INTEGER,
  users INTEGER,
  pageviews INTEGER,
  bounce_rate REAL,
  avg_visit_duration_seconds REAL,
  dataset_coverage TEXT NOT NULL,
  freshness TEXT NOT NULL,
  comparability TEXT NOT NULL,
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  supersedes_fact_id INTEGER,
  superseded_by_fact_id INTEGER,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_fact_id) REFERENCES traffic_metrics(fact_id) ON DELETE RESTRICT,
  FOREIGN KEY (superseded_by_fact_id) REFERENCES traffic_metrics(fact_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS index_coverage (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL,
  source TEXT NOT NULL,
  effective_at TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  index_state TEXT NOT NULL,
  problem_severity TEXT NOT NULL DEFAULT '__all__',
  problem_code TEXT NOT NULL DEFAULT '__all__',
  sitemap_id TEXT NOT NULL DEFAULT '__all__',
  searchable_pages INTEGER,
  excluded_pages INTEGER,
  submitted_urls INTEGER,
  indexed_urls INTEGER,
  problem_count INTEGER,
  dataset_coverage TEXT NOT NULL,
  freshness TEXT NOT NULL,
  comparability TEXT NOT NULL,
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS crawl_pages (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source = 'local_crawl'),
  effective_at TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  crawled_url TEXT NOT NULL,
  final_url TEXT NOT NULL,
  depth INTEGER NOT NULL CHECK (depth >= 0),
  fetch_status INTEGER,
  robots_status TEXT NOT NULL CHECK (robots_status IN ('allowed', 'excluded')),
  content_type TEXT,
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  title TEXT NOT NULL DEFAULT '',
  meta_description TEXT NOT NULL DEFAULT '',
  h1_text TEXT NOT NULL DEFAULT '',
  h1_count INTEGER NOT NULL DEFAULT 0 CHECK (h1_count >= 0),
  canonical_url TEXT,
  header_canonical_url TEXT,
  meta_robots TEXT,
  x_robots_tag TEXT,
  hreflang_json TEXT NOT NULL DEFAULT '[]',
  redirect_chain_json TEXT NOT NULL DEFAULT '[]',
  internal_links_json TEXT NOT NULL DEFAULT '[]',
  error TEXT,
  dataset_coverage TEXT NOT NULL CHECK (dataset_coverage IN ('complete', 'truncated', 'privacy_thresholded', 'unknown', 'unavailable')),
  freshness TEXT NOT NULL CHECK (freshness IN ('provisional', 'final', 'stale')),
  comparability TEXT NOT NULL CHECK (comparability IN ('comparable', 'config_break', 'protocol_break', 'population_mismatch', 'insufficient_history', 'window_mismatch')),
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  supersedes_fact_id INTEGER,
  superseded_by_fact_id INTEGER,
  content_hash TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_fact_id) REFERENCES crawl_pages(fact_id) ON DELETE RESTRICT,
  FOREIGN KEY (superseded_by_fact_id) REFERENCES crawl_pages(fact_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crawl_pages_current
  ON crawl_pages(project_id, property_id, logical_observation_key)
  WHERE is_current = 1;

CREATE TABLE IF NOT EXISTS outcome_metrics (
  fact_id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  source TEXT NOT NULL,
  effective_start TEXT NOT NULL,
  effective_end TEXT NOT NULL,
  source_timezone TEXT NOT NULL,
  effective_instant_start TEXT NOT NULL,
  effective_instant_end TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  artifact_id TEXT NOT NULL,
  logical_observation_key TEXT NOT NULL,
  collection_attempt_key TEXT NOT NULL,
  outcome_id TEXT NOT NULL,
  evidence_kind TEXT NOT NULL CHECK (evidence_kind IN ('analytics_event', 'server_fact')),
  counting_unit TEXT NOT NULL,
  deduplication_rule TEXT NOT NULL,
  population_scope TEXT NOT NULL,
  attribution_model TEXT NOT NULL DEFAULT '__all__',
  attribution_scope TEXT NOT NULL,
  traffic_channel TEXT NOT NULL DEFAULT '__all__',
  search_engine TEXT NOT NULL DEFAULT '__all__',
  landing_page_id TEXT NOT NULL DEFAULT '__all__',
  device TEXT NOT NULL DEFAULT '__all__',
  attribution_level TEXT NOT NULL CHECK (attribution_level IN ('visit_exact', 'channel_aggregate', 'landing_page_aggregate', 'server_aggregate', 'unattributed')),
  count INTEGER,
  unique_actors INTEGER,
  value_minor INTEGER,
  currency TEXT,
  dataset_coverage TEXT NOT NULL,
  freshness TEXT NOT NULL,
  comparability TEXT NOT NULL,
  fact_schema_version INTEGER NOT NULL,
  normalizer_version TEXT NOT NULL,
  is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
  supersedes_fact_id INTEGER,
  superseded_by_fact_id INTEGER,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT,
  FOREIGN KEY (artifact_id) REFERENCES raw_artifacts(artifact_id) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_fact_id) REFERENCES outcome_metrics(fact_id) ON DELETE RESTRICT,
  FOREIGN KEY (superseded_by_fact_id) REFERENCES outcome_metrics(fact_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS competitor_metrics (
  metric_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  normalized_domain TEXT NOT NULL,
  keyword_set_id TEXT NOT NULL,
  visibility_score REAL NOT NULL,
  formula_version TEXT NOT NULL,
  top3_count INTEGER NOT NULL DEFAULT 0,
  top10_count INTEGER NOT NULL DEFAULT 0,
  gained_keywords INTEGER NOT NULL DEFAULT 0,
  lost_keywords INTEGER NOT NULL DEFAULT 0,
  is_new_competitor INTEGER NOT NULL DEFAULT 0 CHECK (is_new_competitor IN (0, 1)),
  is_disappeared_competitor INTEGER NOT NULL DEFAULT 0 CHECK (is_disappeared_competitor IN (0, 1)),
  page_type TEXT NOT NULL DEFAULT '__all__',
  input_fact_ids_json TEXT NOT NULL,
  calculated_at TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS content_coverage (
  coverage_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  reporting_period_id TEXT NOT NULL,
  coverage_type TEXT NOT NULL,
  covered_count INTEGER NOT NULL DEFAULT 0,
  expected_count INTEGER,
  coverage_ratio REAL,
  evidence_json TEXT NOT NULL,
  request_id TEXT,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS derived_metrics (
  metric_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  formula_id TEXT NOT NULL,
  formula_version TEXT NOT NULL,
  dimensions_json TEXT NOT NULL,
  value REAL,
  unit TEXT NOT NULL,
  comparison_window_json TEXT NOT NULL,
  input_request_ids_json TEXT NOT NULL DEFAULT '[]',
  input_metric_ids_json TEXT NOT NULL DEFAULT '[]',
  quality_json TEXT NOT NULL,
  calculated_at TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS competitor_discovery_runs (
  run_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  source TEXT NOT NULL,
  request_id TEXT,
  target_domain TEXT NOT NULL,
  provider_mode TEXT NOT NULL CHECK (provider_mode IN ('fixture', 'artifact', 'live')),
  quality TEXT NOT NULL,
  cost_usd REAL NOT NULL DEFAULT 0,
  observed_at TEXT NOT NULL,
  artifact_manifest_path TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS competitor_candidates (
  candidate_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  run_id TEXT NOT NULL,
  source TEXT NOT NULL,
  request_id TEXT,
  target_domain TEXT NOT NULL,
  competitor_domain TEXT NOT NULL,
  intersections INTEGER NOT NULL DEFAULT 0,
  organic_keywords INTEGER NOT NULL DEFAULT 0,
  estimated_traffic REAL NOT NULL DEFAULT 0,
  quality TEXT NOT NULL,
  cost_usd REAL NOT NULL DEFAULT 0,
  observed_at TEXT NOT NULL,
  evidence_json TEXT NOT NULL DEFAULT '{}',
  UNIQUE (run_id, competitor_domain),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (run_id) REFERENCES competitor_discovery_runs(run_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS keyword_gap_rows (
  gap_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  property_id TEXT NOT NULL DEFAULT '__all__',
  run_id TEXT NOT NULL,
  source TEXT NOT NULL,
  request_id TEXT,
  target_domain TEXT NOT NULL,
  competitor_domain TEXT NOT NULL DEFAULT '__all__',
  competitor_domains_json TEXT NOT NULL DEFAULT '[]',
  keyword_set_id TEXT,
  keyword_set_hash TEXT,
  keyword TEXT NOT NULL,
  normalized_keyword TEXT NOT NULL,
  location_code TEXT,
  location_name TEXT,
  language_code TEXT,
  best_competitor_rank INTEGER,
  representative_competitor_url TEXT,
  search_volume INTEGER NOT NULL DEFAULT 0,
  cpc REAL NOT NULL DEFAULT 0,
  quality TEXT NOT NULL,
  cost_usd REAL NOT NULL DEFAULT 0,
  observed_at TEXT NOT NULL,
  citation_ids_json TEXT NOT NULL DEFAULT '[]',
  UNIQUE (run_id, normalized_keyword, location_code, location_name, language_code),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT,
  FOREIGN KEY (run_id) REFERENCES competitor_discovery_runs(run_id) ON DELETE RESTRICT,
  FOREIGN KEY (request_id) REFERENCES source_requests(request_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS seo_actions (
  action_id TEXT NOT NULL,
  project_id TEXT NOT NULL,
  changed_at TEXT NOT NULL,
  action_type TEXT NOT NULL,
  description TEXT NOT NULL,
  hypothesis_id TEXT NOT NULL,
  evidence_ref TEXT NOT NULL,
  lifecycle_state TEXT NOT NULL CHECK (lifecycle_state IN ('planned', 'active', 'done', 'tombstoned')),
  action_revision_hash TEXT NOT NULL,
  supersedes_action_revision_hash TEXT,
  PRIMARY KEY (action_id, action_revision_hash),
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS action_targets (
  target_id INTEGER PRIMARY KEY AUTOINCREMENT,
  action_id TEXT NOT NULL,
  action_revision_hash TEXT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('property', 'url', 'query', 'keyword_set', 'segment')),
  target_value TEXT NOT NULL,
  target_role TEXT NOT NULL CHECK (target_role IN ('primary', 'guardrail')),
  FOREIGN KEY (action_id, action_revision_hash)
    REFERENCES seo_actions(action_id, action_revision_hash) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS measurement_windows (
  window_id TEXT NOT NULL,
  action_id TEXT NOT NULL,
  action_revision_hash TEXT NOT NULL,
  baseline_start TEXT NOT NULL,
  baseline_end TEXT NOT NULL,
  observation_start TEXT NOT NULL,
  observation_end TEXT NOT NULL,
  timezone TEXT NOT NULL,
  comparison_strategy TEXT NOT NULL,
  minimum_denominator INTEGER,
  earliest_evaluation_date TEXT NOT NULL,
  confounder_notes TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (window_id, action_revision_hash),
  FOREIGN KEY (action_id, action_revision_hash)
    REFERENCES seo_actions(action_id, action_revision_hash) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS action_verdicts (
  verdict_id TEXT PRIMARY KEY,
  action_id TEXT NOT NULL,
  action_revision_hash TEXT NOT NULL,
  window_id TEXT NOT NULL,
  verdict TEXT NOT NULL CHECK (verdict IN ('positive', 'negative', 'inconclusive', 'not_ready')),
  absolute_delta REAL,
  relative_delta REAL,
  input_derived_metric_ids_json TEXT NOT NULL DEFAULT '[]',
  input_fact_set_hash TEXT NOT NULL,
  evidence_set_hash TEXT NOT NULL,
  historical_snapshot_hashes_json TEXT NOT NULL DEFAULT '[]',
  comparability_state TEXT NOT NULL,
  evaluation_policy_version TEXT NOT NULL,
  evaluation_as_of TEXT NOT NULL,
  supersedes_verdict_id TEXT,
  explanation TEXT NOT NULL,
  FOREIGN KEY (action_id, action_revision_hash)
    REFERENCES seo_actions(action_id, action_revision_hash) ON DELETE RESTRICT,
  FOREIGN KEY (window_id, action_revision_hash)
    REFERENCES measurement_windows(window_id, action_revision_hash) ON DELETE RESTRICT,
  FOREIGN KEY (supersedes_verdict_id) REFERENCES action_verdicts(verdict_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS snapshot_manifests (
  manifest_id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  reporting_period_id TEXT NOT NULL,
  snapshot_schema_version INTEGER NOT NULL,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  timezone TEXT NOT NULL,
  generated_at TEXT NOT NULL,
  source_quality_json TEXT NOT NULL,
  snapshot_hash TEXT NOT NULL,
  report_hash TEXT,
  logical_evidence_ids_json TEXT NOT NULL,
  local_attempt_receipt_json TEXT NOT NULL,
  renderer_version TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE RESTRICT
);
